### ISSUE TITLE
After installing pizpalue_distribution there are noch demo sites or folder in the page tree

### ISSUE THREAD

**Issue by schorsch8878** [buepro/typo3-pizpalue_distribution#1]
After installing pizpalue_distribution there are noch demo sites or folder in the page tree. I tested with typo3 10.4.17 many times.

Many thanks

**Comment by buepro** [comment]
Thank you for reporting. This could be related to the memory limit. Do you have the possibility to use 512MB (`memory_limit`)?

**Comment by schorsch8878** [comment]
Hello, thanks for your post. I increased the memory limit to 512M and now it works!!
