### ISSUE TITLE
Schema element - meta description with newline -> error

### ISSUE THREAD

**Issue by ste101** [buepro/typo3-pizpalue_distribution#2]
If the page meta tag field description contains a newline the SchemaViewHelper will show 
`Decoding the string to json didn't result in a array ...`

Please change the line 
`"description":"{parentData:field:description}",`
to
`"description":"{func:newLineToRn:{parentData:field:description}}",`

**Comment by buepro** [comment]
Thank you for reporting this issue. It is corrected in v2.0.6.
